--- #YAML:1.0
name:                HTML-TreeBuilder-XPath
version:             0.11
abstract:            add XPath support to HTML::TreeBuilder
license:             perl
author:              
    - Michel Rodriguez <mrodrigu@localdomain>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    HTML::TreeBuilder:             0
    List::Util:                    0
    XML::XPathEngine:              0.12
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
