--- #YAML:1.0
name:                HTML-TreeBuilder-XPath
version:             0.08
abstract:            add XPath support to HTML::TreeBuilder
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    HTML::TreeBuilder:             0
    XML::XPathEngine:              0.08
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Michel Rodriguez <mrodrigu@localdomain>
