--- #YAML:1.0
name:               HTML-TreeBuilder-XPath
version:            0.13
abstract:           add XPath support to HTML::TreeBuilder
author:
    - Michel Rodriguez <mrodrigu@localdomain>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTML::TreeBuilder:  0
    List::Util:         0
    XML::XPathEngine:   0.12
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
