# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-TreeBuilder-XPath
version:      0.06
version_from: lib/HTML/TreeBuilder/XPath.pm
installdirs:  site
requires:
    HTML::TreeBuilder:             0
    XML::XPathEngine:              0.03

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
